### PR TITLE
chore(chart): check CRDs available before installing prometheus resources

### LINKED ISSUE #107: Helm Chart - Check prometheus CRD availability before creating ServiceMonitor - PodMonitor - PrometheusRule  resources
Given that the prometheus-stack dependency can be disabled (see `condition: kube-prometheus-stack.install`), adding a couple of guardrails to prometheus resources might make sense:

- `templates/podmonitors.yaml`
- `templates/prometheusRules.yaml`
- `templates/servicemonitors.yaml`

### PR DESCRIPTION
**Pull request by cmontemuino**
Prometheus  resources should not be rendered unless Prometheus CRDs are available.

This changeset includes an extra option to override the `apiVersion` Prometheus provides.

close https://github.com/openebs/monitoring/issues/107

### CODE REVIEW

**Comment by avishnu** [comment]
There is a conflict that needs resolution.

**Comment by abhilashshetty04** [comment]
Hi @cmontemuino , Thanks for thr PR. Can you please remove chart bump from your commit. We will cherry-pick your commit on PR which will have chart bump.

**Comment by cmontemuino** [comment]
> Hi @cmontemuino , Thanks for thr PR. Can you please remove chart bump from your commit. We will cherry-pick your commit on PR which will have chart bump.

Hi @abhilashshetty04. I did a rebase against latest changes and kept file `Chart.yaml` unchanged.

**Comment by cmontemuino** [comment]
Changes from this PR have been cherry-picked in https://github.com/openebs/monitoring/pull/119

**Pull request closed without merging**
