### PR TITLE
chore(alerting): disable npd dashboard and alert rules

### PR DESCRIPTION
**Pull request by abhilashshetty04**

### CODE REVIEW

**Review by avishnu — APPROVED** [review]
Do we need any bump on the chart version?

**Comment by abhilashshetty04** [comment]
> Do we need any bump on the chart version?

Yes we should. Now im thinking i could have added this as a separate commit in the PR https://github.com/openebs/monitoring/pull/119 . Could have bumped version there. 

Can still do that @niladrih wdyt? We can close this PR

**Comment by avishnu** [comment]
> > Do we need any bump on the chart version?
> 
> Yes we should. Now im thinking i could have added this as a separate commit in the PR #119 . Could have bumped version there.
> 
> Can still do that @niladrih wdyt? We can close this PR

Let's merge the PR

**Comment by niladrih** [comment]
This change won't be availble via this helm chart without releasing a new version.

**Comment by abhilashshetty04** [comment]
> > > Do we need any bump on the chart version?
> > 
> > 
> > Yes we should. Now im thinking i could have added this as a separate commit in the PR #119 . Could have bumped version there.
> > Can still do that @niladrih wdyt? We can close this PR
> 
> Let's merge the PR

CI Fails without chart version bump. I feel we have to merge this on PR where we bump chart version.

**Comment by abhilashshetty04** [comment]
Closing this as we added changes in https://github.com/openebs/monitoring/pull/120 with version bump

**Pull request closed without merging**
